ignored:
  # allow relative WORKDIR
  - DL3000
  # ignore apt version pinning
  - DL3008
  # ignore pip version pinning
  - DL3013
  # ignore apk version pinning
  - DL3018
  # allow multiple consecutive RUN
  - DL3059
