name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry'
        default: &DOCKER_REGISTRY docker.io
        type: string
      namespace:
        description: 'Docker namespace'
        default: &DOCKER_NAMESPACE koreader
        type: string
      images:
        description: 'Build the specified images (empty: build all)'
        required: false
        type: string
      nodeps:
        description: 'Ignore dependencies between images (only build the specified images)'
        type: boolean
      rebuild:
        description: 'Force rebuilding images (including their dependencies if not ignored)'
        type: boolean
      publish:
        description: 'Publish images to registry'
        type: boolean
      lint:
        description: 'Run lint job'
        type: boolean

defaults:
  run:
    shell: bash


jobs:

  lint:

    if: github.event.inputs == null || inputs.lint

    name: Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          clean: false
          fetch-depth: 1
          show-progress: false

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          set -x
          ./docker/ubuntu/scripts/install_hadolint.sh
          ./docker/ubuntu/scripts/install_uv.sh
          uv pip install --system pylint -r ./docker/ubuntu/nightswatcher/requirements.txt

      - name: Lint
        run: make -s -C docker/ubuntu lint --output-sync -j$(nproc) -k


  prepare:

    name: Prepare
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          clean: false
          fetch-depth: 1
          show-progress: false

      - name: Install regctl
        run: ./docker/ubuntu/scripts/install_regctl.sh

      - name: Generate outputs
        id: generate
        env:
          DOCKER_REGISTRY: *DOCKER_REGISTRY
          DOCKER_NAMESPACE: *DOCKER_NAMESPACE
        run: |
          exec 2>&1 # avoid jumbled output…
          printf '::group::generate\n'
          set -x
          images=(${{ inputs.images }})
          registry='${{ inputs.registry || env.DOCKER_REGISTRY }}'
          namespace='${{ inputs.namespace || env.DOCKER_NAMESPACE }}'
          rebuild=${{ github.event.inputs != null && inputs.rebuild && 'true' || '' }}
          publish=${{ (github.event.inputs == null && github.ref == vars.DOCKER_PUBLISH_REF || inputs.publish) && 'true' || '' }}
          nodeps=${{ github.event.inputs != null && inputs.nodeps && 'true' || '' }}
          matrix=docker/ubuntu/build/ci_matrix.json
          make -s -C docker/ubuntu -j$(nproc) \
            REGISTRY="${registry}" NAMESPACE="${namespace}" \
            ${nodeps:+IMAGE_BASE=scratch} ${rebuild:+REGCTL=false} \
            ${images:+"CI_MATRIX_IMAGES=${images[*]}"} ci-matrix
          jq --compact-output <"${matrix}" | sed 's/^/matrix=/' | tee -a "${GITHUB_OUTPUT}"
          max_parallel="$(jq 'if [.[]|.base]|any then 1 else length end' "${matrix}")"
          printf '%s=%s\n' max_parallel "${max_parallel}" publish "${publish:-false}" registry "${registry}" namespace "${namespace}" | tee -a "${GITHUB_OUTPUT}"
          set +x
          printf '::endgroup::\n'
          jq --color-output <"${matrix}"

    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      max_parallel: ${{ steps.generate.outputs.max_parallel }}
      publish: ${{ steps.generate.outputs.publish }}
      registry: ${{ steps.generate.outputs.registry }}
      namespace: ${{ steps.generate.outputs.namespace }}


  build:

    needs: [prepare, lint]
    if: |
      !cancelled() &&
      needs.prepare.outputs.matrix &&
      contains('skipped success', needs.lint.result)

    strategy:
      max-parallel: ${{ fromJSON(needs.prepare.outputs.max_parallel) }}
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    name: Build ${{ matrix.id }}

    uses: ./.github/workflows/build.image.yml
    secrets:
      # Yep, this is required to allow the use of the `docker` environment
      # secret of the same name in the called workflow… Pretty evident,
      # right? ¯\_(ツ)_/¯
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    with:
      id: ${{ matrix.id }}
      image: ${{ matrix.image }}
      base: ${{ matrix.base }}
      platform: ${{ matrix.platform }}
      publish: ${{ fromJSON(needs.prepare.outputs.publish) }}
      registry: ${{ needs.prepare.outputs.registry }}
      namespace: ${{ needs.prepare.outputs.namespace }}
