name: Build Image

on:
  workflow_call:
    inputs:
      id:
        required: true
        type: string
      image:
        required: true
        type: string
      base:
        required: true
        type: string
      platform:
        required: true
        type: string
      publish:
        required: true
        type: boolean
      registry:
        required: true
        type: string
      namespace:
        required: true
        type: string
    secrets:
      DOCKER_TOKEN:
        required: true

defaults:
  run:
    shell: bash


jobs:


  build:

    strategy:
      matrix:
        platform: ${{ fromJSON(inputs.platform) }}

    name: ${{ matrix.platform }}
    runs-on: ${{ startsWith(matrix.platform, 'arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    env:
      MAKEFLAGS: -s REGISTRY=${{ inputs.registry }} NAMESPACE=${{ inputs.namespace }} PLATFORM=${{ matrix.platform }}
      TAR: ${{ inputs.id }} ${{ matrix.platform }}.tar

    steps:

      - &CHECKOUT
        name: Checkout
        uses: actions/checkout@v5
        with:
          clean: false
          fetch-depth: 1
          show-progress: false

      - &INSTALL_REGCTL
        name: Install regctl
        run: ./docker/ubuntu/scripts/install_regctl.sh

      - name: Download base image from artifacts
        if: inputs.base
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.base }} ${{ matrix.platform }}

      - name: Load base image
        if: inputs.base
        run: docker load -i '${{ inputs.base }} ${{ matrix.platform }}.tar'

      - name: Build image
        run: make -C docker/ubuntu ${{ inputs.image }}

      - name: Save image
        run: make -C docker/ubuntu ${{ inputs.image }}/save TAR="${PWD}/${TAR}"

      - name: Compress image layers
        env:
          COMPRESSION: zstd
        run: |
          du -h "$TAR"
          printf '::group::compress\n'
          set -x
          regctl image import ocidir://oci "${TAR}"
          regctl image mod --layer-compress ${COMPRESSION} ocidir://oci --create ocidir://oci:${COMPRESSION}
          regctl image export --name ${{ inputs.image }} ocidir://oci:${COMPRESSION} "${TAR}"
          set +x
          printf '::endgroup::\n'
          du -h "$TAR"

      - name: Upload image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.id }} ${{ matrix.platform }}
          path: ${{ env.TAR }}
          if-no-files-found: error
          compression-level: 0
          retention-days: 1


  publish:

    needs: build
    if: inputs.publish

    name: publish
    runs-on: ubuntu-latest
    environment: docker

    steps:

      - *CHECKOUT

      - *INSTALL_REGCTL

      - name: Log in to the registry
        env:
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: regctl registry login '${{ inputs.registry }}' --user '${{ vars.DOCKER_USER }}' --pass-stdin <<<"${PASSWORD}"

      - name: Download platform images from artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: ${{ inputs.id }} *
          merge-multiple: true

      - name: Aggregate & publish final image
        run: |
          set -x
          command=(regctl index create -v info)
          for tar in *.tar; do
            ocidir="ocidir://${tar%.tar}"
            regctl image import "${ocidir}" "${tar}"
            command+=(--ref "${ocidir}")
          done
          "${command[@]}" ${{ inputs.image }}
